# Generated by Django 2.0.6 on 2018-08-24 14:21

from django.db import migrations
from django.db.utils import ProgrammingError


def create_userplans(apps, schema_editor):
    from plans.base.models import AbstractUserPlan

    try:
       AbstractUserPlan.get_concrete_model().create_for_users_without_plan()
    except ProgrammingError:
       print('\n\n', '*' * 150)
       print('**', "Perhaps your User model is using django-tenants.")
       print('**', "please run 'python manage.py migrate_schemas --shared' again")
       print('\n\n', '*' * 150)


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_make_plans_unique"),
    ]

    operations = [
        migrations.RunPython(create_userplans, reverse_code=migrations.RunPython.noop),
    ]
